### ISSUE TITLE
[ Errors in some structures with Releases ]

### ISSUE THREAD

**Issue by JoaquinViera** [grupomises/onsas#63]
Differences with the analytical solution. The problem may be in the assembly of the matrix and the dree of freedoms.

File name: R2_pr3_ej3.m

**Comment by jorgepz** [comment]
@JoaquinViera , agregué un ejemplo simple donde se puede ver la solución con y sin articulaciones en un elemento. https://github.com/grupomises/onsas/blob/jorge/input/onsas_input_validateMixedElements.m
Se puede ver que el valor de desplazamiento del extremo cambia al articular los extremos de la barra 2-4, por lo tanto creo que el ensamblado de K no necesariamente está mal... Creo que el error podría estar en el cálculo de dispsElemsMat cerca de las líneas 480 de linearAnalysis.m
